name: Päivitä Lounaslista

on:
  schedule:
    - cron: '0 3-10 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write # Varmistaa, että GitHub Actions saa tallentaa lounas.html-tiedoston

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Helsinki' # Pakotetaan Suomen aika
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Piilottaa harmittoman Node.js-varoituksen

    steps:
      - name: Hae koodi
        uses: actions/checkout@v4

      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Asenna suomen kieli (Factorya ja PORia varten)
        run: sudo apt-get install -y language-pack-fi

      - name: Asenna riippuvuudet
        run: pip install -r requirements.txt

      - name: Aja skripti
        run: python lounaskaikki2.py

      - name: Tallenna luotu HTML GitHubiin
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automaattinen lounaslistan päivitys"
